In [3]:
import numpy as np
an_array = np.array([3, 33, 333])
print(type(an_array))

<class 'numpy.ndarray'>


In [4]:
print(an_array.shape)

(3,)


In [5]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [10]:
an_array[0]=888

print(an_array)

[888  33 333]


In [15]:
another = np.array([[11,12,13],[21,22,23]])

print(another)
print("The shape is 2 rows, 3 columns:", another.shape)

another[0,0]

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns: (2, 3)


11

In [17]:
print(another)

[[11 12 13]
 [21 22 23]]


In [19]:
%%HTML
<H1> Toto </H1>